spring:
  application:
    name: wallet-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/wallet_service?ApplicationName=wallet-service
    username: ylab
    password: ylab
  liquibase:
    default-schema: app
    liquibase-schema: liquibase
    change-log: db/changelog/changelog.xml

  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8081

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: Grigoriy
  user: User
  system: System