database:
  driver-class-name: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5433/wallet_service"
  user: "ylab"
  password: "ylab"
  default-schema: "app"
  liquibase-schema: "liquibase"

liquibase:
  changelog-file: "db/changelog/changelog.xml"

jwt:
  secret: "NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw"
  issuer: "Grigoriy"
  user: "User"
  system: "System"